### ISSUE TITLE
Add solutions for tasks

### ISSUE THREAD

**Issue by Alacho2** [BeiningBogen/iOS-Kristiania#2]
👍

**Comment by BlackCapCoder** [comment]
If this is implemented it might pave the way for a test suit.

I am obviously not familiar with the swift ecosystem, but with `quickcheck` in haskell you could just:
```haskell
task1 = error "Not implemented"
...
task1 `shouldBe` task1_solution
```
Surely you have something similar in swift?

**Comment by Alacho2** [comment]
I don't understand what your answer has to do with my request.

**Comment by Alacho2** [comment]
@MrHaze bump on this.

**Comment by Breiby** [comment]
Added proposed solutions for the the first three lessons. Will look into the rest if/when there is time. Pull-requests are welcome! 😊
